# This is a <PART> of URL in the template /products/<PART>/
productCode: prompp

priorityClassName:
  _default: develop
  production: production-medium
  web-production: production-medium

ingressClass:
  _default: nginx

certificateClusterIssuer:
  _default: letsencrypt
  production: letsencrypt-nginx

resources:
  requests:
    memory:
      _default: 32M
      web-production: 150M

resolver: kube-dns.kube-system.svc.cluster.local
