name: Build

on:
  pull_request_target:
     types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Hugo Site
    container:
      image: hugomods/hugo:debian-ci-0.150.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Mark repository as safe
        run: git config --global --add safe.directory '${{ github.workspace }}'

      - name: Build Hugo site
        run: hugo --minify --enableGitInfo=false

      - name: Install htmltest
        run: |
          curl https://htmltest.wjdp.uk | bash

      - name: Check links
        run: bin/htmltest ./public
