name: Lint Markdown

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    name: Lint Markdown Files
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          config: markdownlint.yaml

