name: Lint Markdown

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    name: Lint Markdown Files
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint-cli
        run: |
          docker run --rm -v "$PWD:/workdir" -w /workdir ghcr.io/igorshubovych/markdownlint-cli:v0.45.0 "**/*.md" -c markdownlint.yaml

